AllCops:
  Include:
    - 'app/controllers/api/*.rb'
    - 'app/models/*.rb'
  Exclude:
    - 'bin/*'
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/api/*.rb'
    - 'app/models/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/controllers/api/*.rb'
    - 'app/models/*.rb'
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Max: 95
Style/CaseLikeIf:
  Enabled: false